/**
 * Types for the RAG-based Question Detection & Answering feature.
 *
 * These types correspond to the backend Pydantic models in:
 * - backend/app/question_detector.py
 * - backend/app/rag_engine.py
 * - backend/app/document_indexer.py
 */

/** A question detected in a meeting transcript. */
export interface DetectedQuestion {
    text: string;
    start_index: number;
    end_index: number;
    confidence: number;
}

/** Response from the /detect-questions endpoint. */
export interface DetectQuestionsResponse {
    questions: DetectedQuestion[];
}

/** Request to detect questions in transcript text. */
export interface DetectQuestionsRequest {
    transcript_text: string;
}

/** A source reference from the knowledge base. */
export interface RAGSource {
    filename: string;
    text_preview: string;
    distance: number | null;
}

/** An answer generated by the RAG pipeline. */
export interface RAGAnswer {
    question: string;
    answer: string;
    sources: RAGSource[];
    confidence: number;
}

/** Request to ask a question using the RAG pipeline. */
export interface AskQuestionRequest {
    question: string;
    meeting_context?: string;
    model?: string;
    model_name?: string;
    n_results?: number;
}

/** Request to ask a question using direct file context (no vectorization).
 *  Files are read ephemerally — content is never stored in a database. */
export interface AskQuestionWithContextRequest {
    question: string;
    meeting_context?: string;
    file_paths: string[];
    model?: string;
    model_name?: string;
}

/** Preview of a context file's content. */
export interface ContextFilePreview {
    filename: string;
    file_path: string;
    text_preview: string;
    text_length: number;
}

/** Metadata about an indexed document. */
export interface DocumentMetadata {
    doc_id: string;
    filename: string;
    file_path: string;
    file_type: string;
    chunk_count: number;
    file_hash: string;
}

/** Request to index a single file. */
export interface IndexFileRequest {
    file_path: string;
    chunk_size?: number;
    overlap?: number;
}

/** Request to index a directory of files. */
export interface IndexDirectoryRequest {
    directory_path: string;
    recursive?: boolean;
    chunk_size?: number;
    overlap?: number;
}

/** Knowledge base statistics. */
export interface KnowledgeBaseStats {
    total_chunks: number;
    total_documents: number;
    collection_name: string;
    persist_directory: string;
}

/** Request to search the knowledge base. */
export interface SearchKnowledgeBaseRequest {
    query: string;
    n_results?: number;
}

/** A search result from the knowledge base. */
export interface KnowledgeBaseSearchResult {
    text: string;
    metadata: Record<string, unknown>;
    distance: number | null;
}
